export default [
    {type: 'text', data: 'genome_name', label: 'Genome Name'},
    {type: 'numeric', data: 'genome_id', label: 'Genome ID'},
    {type: 'text', data: 'genome_status', label: 'Genome Status'},
    {type: 'numeric', data: 'contigs', label: 'Contigs'},
    {type: 'numeric', data: 'patric_cds', label: 'Patric CDS'},
    {type: 'text', data: 'isolation_country', label: 'Isolation Country'},
    {type: 'text', data: 'host_name', label: 'Host Name'},
    {type: 'numeric', data: 'collection_year', label: 'Collection Year'},
    {type: 'date', data: 'completion_date', label: 'Completion Date', dateFormat: 'MM/DD/YYYY', correctFormat: true},

    // hide the following
    {type: 'numeric', data: 'plasmids', hide: true},
    {type: 'text', data: 'common_name', hide: true},
    {type: 'text', data: 'isolation_comments', hide: true},
    {type: 'text', data: 'temperature_range', hide: true},
    {type: 'text', data: 'oxygen_requirement', hide: true},
    {type: 'text', data: 'owner', hide: true},
    {type: 'text', data: 'strain', hide: true},
    {type: 'text', data: 'patric_cds', hide: true},
    {type: 'text', data: 'gc_content', hide: true},
    {type: 'text', data: 'refseq_cds', hide: true},
    {type: 'text', data: 'gram_stain', hide: true},
    {type: 'text', data: 'ncbi_project_id', hide: true},
    {type: 'text', data: 'disease', hide: true},
    {type: 'text', data: 'sequencing_depth', hide: true},
    {type: 'text', data: 'organism_name', hide: true},
    {type: 'text', data: 'isolation_source', hide: true},
    {type: 'text', data: 'genome_name', hide: true},
    {type: 'text', data: 'sequencing_centers', hide: true},
    {type: 'text', data: 'genome_length', hide: true},
    {type: 'text', data: 'cell_shape', hide: true},
    {type: 'text', data: 'comments', hide: true},
    {type: 'text', data: 'genbank_accessions', hide: true},
    {type: 'text', data: 'refseq_project_id', hide: true},
    {type: 'text', data: 'optimal_temperature', hide: true},
    {type: 'text', data: 'public', hide: true},
    {type: 'text', data: 'sequencing_status', hide: true},
    {type: 'text', data: 'p2_genome_id', hide: true},
    {type: 'text', data: 'refseq_accessions', hide: true},
    {type: 'text', data: 'sequencing_platform', hide: true},
    {type: 'text', data: 'chromosomes', hide: true},
    {type: 'text', data: 'taxon_id', hide: true},
    {type: 'text', data: 'habitat', hide: true},
    {type: 'text', data: 'taxon_lineage_ids', hide: true},
    {type: 'text', data: 'taxon_lineage_names', hide: true},
    {type: 'text', data: 'phylum', hide: true},
    {type: 'text', data: 'order', hide: true},
    {type: 'text', data: 'genus', hide: true},
    {type: 'text', data: 'species', hide: true},
    {type: 'text', data: 'kingdom', hide: true},
    {type: 'text', data: 'class', hide: true},
    {type: 'text', data: 'family', hide: true},
    {type: 'text', data: 'date_inserted', hide: true},
    {type: 'text', data: 'date_modified', hide: true},
    {type: 'text', data: 'bioproject_accession', hide: true},
    {type: 'text', data: 'biosample_accession', hide: true},
    {type: 'text', data: 'assembly_accession', hide: true},
    {type: 'text', data: 'plfam_cds', hide: true},
    {type: 'text', data: 'partial_cds', hide: true},
    {type: 'text', data: 'cds', hide: true},
    {type: 'text', data: 'contig_l50', hide: true},
    {type: 'text', data: 'hypothetical_cds', hide: true},
    {type: 'text', data: 'trna', hide: true},
    {type: 'text', data: 'rrna', hide: true},
    {type: 'text', data: 'cds_ratio', hide: true},
    {type: 'text', data: 'partial_cds_ratio', hide: true},
    {type: 'text', data: 'contig_n50', hide: true},
    {type: 'text', data: 'genome_quality', hide: true},
    {type: 'text', data: 'hypothetical_cds_ratio', hide: true},
    {type: 'text', data: 'plfam_cds_ratio', hide: true},
    {type: 'text', data: 'coarse_consistency', hide: true},
    {type: 'text', data: 'fine_consistency', hide: true},
    {type: 'text', data: 'checkm_completeness', hide: true},
    {type: 'text', data: 'checkm_contamination', hide: true},

]
